# Browser
cask "duckduckgo"

# Messagging
cask "telegram"
cask "discord"
cask "whatsapp"

# GUI stuff for development
cask "raycast"
cask "wezterm"
cask "godot-mono"
cask "dotnet-sdk"

# Notes
cask "obsidian"

# Playing stuff
cask "melonds"
